spring:
  
    mvc:
        static-path-pattern: /static/**
    resources:
        static-locations: classpath:/static/
        add-mappings: true
    
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://15.165.216.51:3306/countuser?allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
        username: SCOTT
        password: TIGER
logging.file: /var/log/requestloggingweb.log

server: 
    port: 443
