spring:
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc:
        static-path-pattern: /**

    resources:
        static-locations: classpath:/
        add-mappings: true
    
        
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://ENC(vDSKLFJVKJskjd20+aA==):3306/dayoff?allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
        username: ENC(vJTKRmElgUSVFmf27G3+RA==)
        password: ENC(vJTKRmElgUSVFmf27G3+RA==)
logging.file: /var/log/requestloggingweb.log

server: 
    port: 443  


